name: Render and Deploy

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Render
        run: ./render.sh

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          path: main.pdf

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "website"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
